# -*- coding: utf-8 -*-
"""PalmerPenguinsM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_NH0ySPH5aXY2q-bz_SV5u51w_rLY0e
"""

# PalmerPenguinsM2.py
# KeylanFralick
# 9/16/26
# Uses lists and formatted output to analyze Palmer penguin statistics.

# constants representing the species and count
import math
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# lists containing speices data
species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

NUM_Chinstrap = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

species_count = [
    NUM_Chinstrap,
    NUM_GENTOO,
    NUM_ADELIE
    ]

# caculate dataset statistics
total_species = len(species_names)
total_penguins = sum(species_count)

average_penguins = total_penguins / total_species
chinstrap_percent = species_count[0] / total_penguins * 100
gentoo_percent = species_count[1] / total_penguins * 100
adelie_percent = species_count[2] / total_penguins* 100
average_penguins_rounded_up = math.ceil(average_penguins)

# determine largest and smallest species groups
largest_count = max(species_count)
smallest_count = min(species_count)
largest_index = species_count.index(largest_count)
smallest_index = species_count.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# output formatted statsitics
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")

print(f"There are a total of {total_species} penguins in this dataset.")
print(f"There are a total of {total_penguins} penguins in the dataset.")

# To display a species count and percentage:
print(f"The average number of penguins per species is "
 f"{average_penguins:.1f}")
print("The average number rounded up is", average_penguins_rounded_up)

print() # This adds a blank space

print(f"{species_names[0]}: {species_count[0]}"
      f" ({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_count[1]}"
      f" ({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_count[2]}"
      f" ({adelie_percent:.2f}%)")

print() # This adds a blank space

print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")